### ISSUE TITLE
Exp Bottle and Enchanted Golden Apple

### ISSUE THREAD

**Issue by QsSmite** [RobiOfficial/Craftable#2]
Hi! Is it possible to add exp bottle crafting recipe and then also enchanted golden apple recipe. It would be great if these recipes are somehow connected.

**Comment by RobiOfficial** [comment]
Hello! Thank you for your request, and yes - this request is doable and can be added to the next plugin update.

**Comment by RobiOfficial** [comment]
These items have been added to the plugin. 
![EnchantedGoldenApple](https://github.com/RobiOfficial/Craftable/blob/main/Recipes/V1.2.0/EnchantedGoldenApple.PNG?raw=true)
![ExpBottle](https://github.com/RobiOfficial/Craftable/blob/main/Recipes/V1.2.0/EnchantedBottle.PNG?raw=true)
